spring.application.name=secure-web-platform-v2
spring.datasource.url=jdbc:postgresql://localhost:5432/secure_web_platform_v2
spring.datasource.username=aidanp.beattie
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update